### ISSUE TITLE
[PE-D][Tester C] Unsure of eligibility for NOC

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-T17-2/tp#108]
The requirement for NOC is 70MCs and completion of CS2113 for CEG students. However, keying in said information still shows that the user is ineligible for NOC. This is naturally up to the group to decide what should their requirements be for the program to output that the user is eligible for NOC and hence adjust their conditions accordingly.

Relevant screenshot:
![image.png](https://raw.githubusercontent.com/joshuan98/ped/main/files/b3e37106-333c-4483-9dd7-3a95ed6d48c2.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: joshuan98/ped#23

**Comment by insafhere** [comment]
This issue is irrelevant as it user has put in wrong value for MC, it has to be within 1-4MC per module. However, this brings up a new issue for users to be able to know specific reasons why they were not eligible for SEP/NOC.
